activities/urls.py
from . import views
from django.urls import path

app_name = 'activities'
urlpatterns = [
    path('', views.index, name='index'),
    path('auth/', views.LoginView.as_view(), name='authenticate'),
    path('activities/', views.activities, name='activities'),
    path('tasks/', views.tasks, name='tasks'),
    path('notifications/', views.notifications, name='notifications'),
    path('<int:activity_id>/', views.activity_details, name='activity_details'),
    path('notification/<int:notification_id>/<int:activity_id>/<int:shown>/', views.activity_details, name='activity_details'),
    path('<int:activity_id>/edit/', views.edit_activity, name='edit'),
    path('<int:parent_project_id>/edit/project/task/<int:task_id>', views.edit_task, name='edit_task'),
    path('<int:task_id>/edit/task/', views.edit_task, name='edit_task'),
    path('<int:parent_project_id>/edit/tasks/', views.choose_project_task, name='choose_project_task'),
    path('<int:project_id>/edit/tasks/', views.choose_project_task_form, name='choose_project_task_form'),
    path('<int:project_id>/edit/project/', views.edit_project, name='edit_project'),
    path('logout/', views.logout_view, name='logout')
]

tasks_assignment_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('activities/', include('activities.urls')),
    path('admin/', admin.site.urls),
]

activities/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django import forms
from datetime import date

default_errors = {
    'required': 'Η συμπλήρωση του πεδίου είναι υποχρεωτική',
    'invalid': 'Η τιμή δεν είναι έγκυρη'
}

def min_date_validator(value):
    if (value is not None):
        if (value < date.today()):
            raise ValidationError('Η ημερομηνία πρέπει να είναι μετά τις ' + date.today().strftime('%m/%d/%Y'))
    else:
        raise ValidationError('Η συμπλήρωση του πεδίου είναι υποχρεωτική')

class LoginForm(AuthenticationForm):
    username = forms.CharField( label='', error_messages=default_errors,
                                widget=forms.TextInput(attrs={'class': 'fadeIn second', 'placeholder': 'Όνομα Χρήστη'}))
    password = forms.CharField( label='', error_messages=default_errors,
                                widget=forms.PasswordInput(attrs={'class': 'fadeIn third', 'placeholder': 'Κωδικός Πρόσβασης'}))

class EditForm(forms.Form):
    title = forms.CharField( label='Τίτλος', error_messages=default_errors,
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Τίτλος'}))
    description = forms.CharField( label='Περιγραφή', required = False, error_messages=default_errors,
                                   widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Περγραφή', }) )
    deadline = forms.DateField( label='Προθεσμία', validators=[min_date_validator], error_messages=default_errors,
                                widget=forms.DateInput(attrs={'type':'date', 'class': 'form-control', 'placeholder': 'Προθεσμία', 'onclick': 'dateFunction()' }))
    receiver = forms.IntegerField( label='Έχετε αναθέσει την αρμοδιότητα στο χρήστη', required = False, error_messages=default_errors,
                                  widget=forms.Select(attrs={'class': 'form-control', }))

    def __init__(self, *args, employee=None, **kwargs):

        self.parent_project_date=kwargs.pop('parent_project_date')
        super(EditForm, self).__init__(*args,**kwargs)

        if (self.parent_project_date is not None):
            self.update_deadline_max(self.parent_project_date)

        if (employee is not None):
            self.set_receiver_choices(employee.receiver_choices())

    def clean(self):
        cleaned_data = super(EditForm, self).clean()

        deadline = cleaned_data.get('deadline')
        parent_project_date = self.parent_project_date
        if (parent_project_date is not None):
            if (deadline > self.parent_project_date):
                raise ValidationError("Προθεσμία: Η ημερομηνία πρέπει να είναι πριν τις " + self.parent_project_date.strftime('%m/%d/%Y'))

    def update_deadline_max(self, max):
        self.fields['deadline'].widget.attrs.update({ 'max': max })

    def set_receiver_choices(self, choices):
        self.fields['receiver'].widget.choices = choices


class SelectForm(forms.Form):
    project_task_id = forms.IntegerField(label='Επιλέξτε μια αρμοδιότητα για να την τροποποιήσετε',
                                         error_messages=default_errors,
                                         widget=forms.Select(attrs={'class': 'form-control',}))

    def set_choices(self, choices):
        self.fields['project_task_id'].widget.choices = choices

activities/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import *
from django.views.generic.edit import FormView
from .forms import LoginForm, EditForm, SelectForm
from django.contrib.auth import login, authenticate, logout
from datetime import date
from django.contrib import messages


""" Index view """
def index(request):
    if (already_authenticated(request)):
        if (request.user.is_officeclerk()):
            return HttpResponseRedirect(reverse('activities:tasks'))
        else:
            return HttpResponseRedirect(reverse('activities:activities'))
    else:
        form = LoginForm()
        return render(request, 'activities/index.html', { 'form': form })


""" Handles the login process """
class LoginView(FormView):
    form_class = LoginForm
    template_name = 'activities/index.html'

    """ Authenticates and logins the user """
    def form_valid(self, form):

        if form is not None:
            credentials = form.cleaned_data

            employee = authenticate(username=credentials['username'],
                            password=credentials['password'])

            return self.login_forward(employee)

    """ Logins and forwards the user to the right page """
    def login_forward(self, employee):

        if employee is not None:
            login(self.request, employee)
            if (employee.is_officeclerk()):
                return HttpResponseRedirect(reverse('activities:tasks'))
            else:
                return HttpResponseRedirect(reverse('activities:activities'))
        else:
            error_message = "Λανθασμένο όνομα χρήστη ή κωδικός πρόσβασης"

        return render(self.request, 'activities/index.html', { 'error_message': error_message, 'form': LoginForm() })


""" Logs the user out """
def logout_view(request):
    logout(request)
    return render(request, 'activities/logout.html')


""" Shows the activities assigned by the user """
def activities(request):
    if (already_authenticated(request)):
        employee = request.user
        activities = employee.activity_sender_set.all().order_by('deadline')
        return render(request, 'activities/activities.html', { 'employee': request.user,
                                                               'activities': activities
                                                              })

    return access_not_allowed(request)


""" Shows user's notifications """
def notifications(request):
    if (already_authenticated(request)):
        employee = request.user
        notifications = employee.receiver_set.all().order_by('-id')
        return render(request, 'activities/notifications.html',
                     { 'employee': request.user,
                       'notifications': notifications
                     })

    return access_not_allowed(request)


""" Shows user's assigned tasks """
def tasks(request):
    if (already_authenticated(request)):
        employee = request.user
        tasks = employee.activity_receiver_set.all().order_by('deadline')
        return render(request, 'activities/tasks.html',
                     { 'employee': request.user,
                       'tasks': tasks
                     })

    return access_not_allowed(request)


""" Renders the right edit template based on the activity type """
def edit_activity(request, activity_id):

    if (not already_authenticated(request)):
        return access_not_allowed(request)

    activity = get_object_or_404(Activity, pk = activity_id)

    employee = request.user
    if (activity.sender == employee):
        form = initialize_edit_form(request, activity)
        if (activity.is_task()):
            task = activity.task
            return render(request, 'activities/edit_task_form.html',
                          { 'employee': employee,
                            'task': task ,
                            'form': form
                          })
        elif (activity.is_project()):
            project = activity.project
            return render(request, 'activities/edit_project_form.html',
                          { 'employee': employee,
                            'project': project,
                            'form': form
                          })

    return access_not_allowed(request)


""" Edits a task """
def edit_task(request, task_id, parent_project_id=0):

    if (not already_authenticated(request)):
        return access_not_allowed(request)

    task = get_object_or_404(Task, pk = task_id)
    employee = request.user

    if (employee == task.sender):
        if (employee.is_departmentdirector()):
            employee = employee.departmentdirector

        if (task.has_parent_project()):
            form = EditForm(request.POST, employee=employee, parent_project_date=task.parent_project_date())
        else:
            form = EditForm(request.POST, employee=employee, parent_project_date=None)

        if (form.is_valid()):
            title = form.cleaned_data['title']
            deadline = form.cleaned_data['deadline']
            description = form.cleaned_data['description']
            receiver_id = form.cleaned_data['receiver']
            receiver = get_object_or_404(Employee, pk=receiver_id)
            previous_title = task.title
            previous_receiver = task.receiver

            task = task.update_activity(title, deadline, description, receiver)

            if (previous_receiver != task.receiver):
                receiver_changed = True
                Notification.objects.create(request.user, receiver, task, 'new_task')
            else:
                receiver_changed= False

            Notification.objects.create(request.user, previous_receiver, task,
                                        'edit_task', previous_title=previous_title, receiver_changed=receiver_changed)

        else:
            if (parent_project_id != 0):
                parent_project = get_object_or_404(Project, pk=parent_project_id)
                return render(request, 'activities/edit_task_form.html', { 'employee': request.user, 'task': task,
                                                                            'form': form, 'parent_project': parent_project })

            return render(request, 'activities/edit_task_form.html', { 'employee': request.user, 'task': task, 'form': form })

        messages.add_message(request, messages.SUCCESS, 'Η αρμοδιότητα τροποποιήθηκε επιτυχώς!')

        if ('done' in request.POST):
            if (parent_project_id != 0 ):
                parent_project = get_object_or_404(Project, pk=parent_project_id)
                return HttpResponseRedirect(reverse('activities:activity_details', kwargs={"activity_id": parent_project.id}))

            return HttpResponseRedirect(reverse('activities:activity_details', kwargs={"activity_id": task_id}))

        elif ('continue' in request.POST):
            parent_project = get_object_or_404(Project, pk=parent_project_id)

            if (parent_project == task.project_field):
                return choose_project_task_form(request, parent_project.id)

    return access_not_allowed(request)


""" Edits a project """
def edit_project(request, project_id):

    if (not already_authenticated(request)):
        return access_not_allowed(request)

    project = get_object_or_404(Project, pk = project_id)

    if (request.user == project.sender):
        form = EditForm(request.POST, parent_project_date=None)

        if (form.is_valid()):
            title = form.cleaned_data['title']
            deadline = form.cleaned_data['deadline']
            description = form.cleaned_data['description']

            project.update_activity(title, deadline, description)

        else:
            return render(request, 'activities/edit_project_form.html',
                          { 'employee': request.user, 'project': project, 'form': form })

        messages.add_message(request, messages.SUCCESS, 'Τα χαρακτηριστικά του έργου τροποποιήθηκαν επιτυχώς!')

        if ('done' in request.POST):
            return HttpResponseRedirect(reverse('activities:activity_details', kwargs={"activity_id": project_id}))
        elif ('continue' in request.POST):
            return choose_project_task_form(request, project.id)

    return access_not_allowed(request)


""" Shows a selection form """
def choose_project_task_form(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    select_form = SelectForm()
    select_form.set_choices(project.get_tasks())

    return render(request, 'activities/choose_project_task.html',
                 { 'employee': request.user, 'form': select_form, 'project': project })


""" Selects which task of a project will be edited """
def choose_project_task(request, parent_project_id):
    if (not already_authenticated(request)):
        return access_not_allowed(request)

    parent_project = get_object_or_404(Project, pk=parent_project_id)

    employee = request.user
    if (employee == parent_project.sender):
        form = SelectForm(request.POST)
        if (form.is_valid()):
            task_id = form.cleaned_data['project_task_id']
            task = get_object_or_404(Task, pk=task_id)

            form = initialize_edit_form(request, task)

            return render(request, 'activities/edit_task_form.html',
                         { 'employee': request.user, 'task': task , 'parent_project': parent_project, 'form': form })
        else:
            form.set_choices(parent_project.get_tasks())
            return render(request, 'activities/choose_project_task.html',
                                  { 'employee': request.user, 'form': form, 'project': parent_project })

    return access_not_allowed(request)


""" Initializes and returns edit form with data based on activity type  """
def initialize_edit_form(request, activity):
    initial= { 'title': activity.title,

activities/templates/activities/base.html
{% load static %}
{% url 'activities:notifications' as notifications_url %}
{% url 'activities:tasks' as tasks_url %}
{% url 'activities:activity_details' as activity_url %}
<!DOCTYPE>
<html>

  <head>
    <title>{% block title %} {% endblock %}</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

	  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'activities/ldbtn.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'activities/loading.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'activities/template.css' %}"/>
  </head>



  <body onload="load()">
    <div class="grid-container">
    {# This is the navbar at the top #}
    <div class="item1">
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          {# This is the header #}
          <div class="navbar-header">
  					<a class="navbar-brand" href="#" style="font-size: 15px;"><span>Δήμος Δάφνης-Υμηττού</span></a>
  				</div>
          {# This is the list #}
          <ul class="nav navbar-nav" id="navbar">
            {% if employee.is_departmentdirector or employee.is_officeclerk %}
              <li class="{% if request.path == tasks_url or receiver %} active {% endif %}"><a href="{% url 'activities:tasks' %}" class="notification"><span class="active">ΟΙ ΑΡΜΟΔΙΟΤΗΤΕΣ ΜΟΥ</span></a></li>
            {% endif %}
            {% if not employee.is_officeclerk %}
            <li><a href="#" class="notification"><span class="active">ΔΗΜΙΟΥΡΓΙΑ ΔΡΑΣΤΗΡΙΟΤΗΤΑΣ</span></a></li>
            <li class="{% if request.path != notifications_url and request.path != tasks_url and receiver is None %} active {% endif %}"><a href="{% url 'activities:activities' %}" class="notification"><span class="active">ΑΝΑΤΕΘΕΙΣΕΣ ΔΡΑΣΤΗΡΙΟΤΗΤΕΣ</span></a></li>
            {% endif %}
            <li class="{% if request.path == notifications_url %} active {% endif %}"><a href="{% url 'activities:notifications'%}" class="notification"><span>ΕΙΔΟΠΟΙΗΣΕΙΣ</span>
              {% if employee.notifications is not None and employee.notifications != 0 %}
              <span class="badge">
                {{ employee.notifications }}
              </span>
              {% endif %}
            </a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><span id="dateTime"></span></a></li>
            {# This is for the media screen #}
            <li><div class="dropdown1">
                <a class="navbar-brand" href="#"style="font-size: 15px;"><span>Δήμος Δάφνης-Υμηττού</span></a>
                  <button class="dropbtn1">
                    <i class="fa fa-bars"></i>
                  </button>
                  <div class="dropdown1-content">
                    <ul>
                      {% if employee.is_departmentdirector or employee.is_officeclerk %}
                        <li class="{% if request.path == tasks_url or receiver %} active {% endif %}"><a href="{% url 'activities:tasks' %}" class="notification"><span class="active">ΟΙ ΑΡΜΟΔΙΟΤΗΤΕΣ ΜΟΥ</span></a></li>
                      {% endif %}
                      {% if not employee.is_officeclerk %}
                      <li><a href="#" class="notification"><span class="active">ΔΗΜΙΟΥΡΓΙΑ ΔΡΑΣΤΗΡΙΟΤΗΤΑΣ</span></a></li>
                      <li class="{% if request.path != notifications_url and request.path != tasks_url and receiver is None %} active {% endif %}"><a href="{% url 'activities:activities' %}" class="notification"><span class="active">ΑΝΑΤΕΘΕΙΣΕΣ ΔΡΑΣΤΗΡΙΟΤΗΤΕΣ</span></a></li>
                      {% endif %}
                      <li class="{% if request.path == notifications_url %} active {% endif %}"><a href="{% url 'activities:notifications'%}" class="notification"><span>ΕΙΔΟΠΟΙΗΣΕΙΣ</span>
                        {% if employee.notifications is not None and employee.notifications != 0 %}
                        <span class="badge">
                          {{ employee.notifications }}
                        </span>
                        {% endif %}
                      </a></li>
                    </ul>
                  </div>
                </div>
            </li>
            {# end of media screen #}
          </ul>
        </div>
      </nav>
    </div>

    {# This is the menu on the left #}
    <div class="item2">
      <div class ="menu">
        <ul>
          <li><a href="#"><span><img src="{% static 'activities/images/profile3.png' %}" alt="εικόνα προφίλ"/>{{ employee.full_name }}</span></a></li>
          <li><a href="#">Τα στοιχεία μου</a></li>
          <li><a href="{% url 'activities:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Αποσύνδεση</a></li>
        </ul>
      </div>
    </div>

    {# This is the main content #}
    <div class="item3">
      <div class=main>
        <div class="container">
        {% block maincontent %}{% endblock %}
        </div>
      </div>
    </div>

    {# This is the footer #}
    <div class="item4">
      <footer id="footer">
        <div class="footer-top">
          <img src="{% static 'activities/images/bulb-1.1s-128px (1).svg' %}" class="ld ld-beat" style="animation-duration:4.0s"/>
          <div class="container">
            <div class="row">
              <div class="col-lg-4 col-md-6 footer-info">
                <h3> OptimizeIt.</h3>
              </div>
              <div class="col-lg-4 col-md-6 footer-links">
                <h4>Πληροφοριες</h4>
                <ul>
                  <li><i class="ion-ios-arrow-right"></i> Ανδρεάδη Θεοδώρα </li>
                  <li><i class="ion-ios-arrow-right"></i> Αντωνογιαννάκη Μαρία-Ελβίρα </li>
                  <li><i class="ion-ios-arrow-right"></i> Γκούλτα Μαρία </li>
                  <li><i class="ion-ios-arrow-right"></i> Περίκου Αικατερίνη </li>
                </ul>
              </div>
              <div class="col-lg-4 col-md-6 footer-links" style="text-align:left;">
                <h4>Επικοινωνηστε μαζι μας</h4>
                <ul class = "list-unstyled">
                  <li><i class="ion-ios-arrow-right"></i> theodoraandreadi@gmail.com </li>
                  <li><i class="ion-ios-arrow-right"></i> eantonog1@gmail.com </li>
                  <li><i class="ion-ios-arrow-right"></i> marygkoulta@gmail.com </li>
                  <li><i class="ion-ios-arrow-right"></i> perikoukaterina@gmail.com </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <div class="container" style="background-color:#262626">
          <div class="copyright">
            <strong> &copy; 2019 Copyright</strong>
          </div>
        </div>
      </footer>

      <div id="back-to-top" class="back-to-top">
        <a href="#item3"><i class="fa fa-chevron-up"></i></a>
      </div>
    </div>


  </div>
  </body>
  <script>

  	document.getElementById("dateTime").innerHTML = formatToGreekDate();

  	function formatToGreekDate(){

  		var date = new Date();
  		var dd = date.getDate();
  		var d = date.getDay();
  		var mm = date.getMonth();
  		var yyyy = date.getFullYear();



  		var greekMonths = ['Ιανουαρίου','Φεβρουαρίου','Μαρτίου','Απριλίου','Μαΐου','Ιουνίου','Ιουλίου','Αυγούστου','Σεπτεμβρίου','Οκτωβρίου','Νοεμβρίου','Δεκεμβρίου'];
  		var greekdays = ['Κυριακή', 'Δευτέρα','Τρίτη','Τετάρτη','Πέμπτη','Παρασκευή','Σάββατο'];

  		return '' + greekdays[d] + ' ' + dd + ' ' + greekMonths[mm] + ' '+ yyyy + ' ';
  	}

    $(document).ready(function () {

    $(window).scroll(function () {
        if ($(window).scrollTop() > 100) {
            $('.back-to-top').fadeIn();
        } else {
            $('.back-to-top').fadeOut();
        }
    });

    $('.back-to-top').on('click', function(e) {
        e.preventDefault();
        $("html, body").animate({
            scrollTop: 0
        }, 1500);

    });
    });

  function load() {
	var trs = $("#tableId tr");
	var btnMore = $("#btn-load-more");
	var x = trs.length;
	var currentIndex = 5;

	trs.hide();
	trs.slice(0, 5).show();
	checkButton();


	btnMore.click(function (e) {
	e.preventDefault();
	$("#tableId tr").slice(currentIndex, currentIndex + 5).show();
    currentIndex += 5;
    checkButton();
});

  function checkButton() {
    var currentLength = $("#tableId tr:visible").length;

    if (currentLength >= x) {
        btnMore.hide();
    } else {
        btnMore.show();
    }


}
}

function loadMore() {
$('.btn').on('click', function() {
    var $this = $(this);
	$this.classList.toggle('loading');

    setTimeout(function() {
       $this.button('reset');
   }, 4000);
});


var trs = $("#tableId tr");
var btnMore = $("#btn-load-more");
var x = trs.length;
var currentIndex = 5;
checkButton();


btnMore.click(function (e) {
	e.preventDefault();
	$("#tableId tr").slice(currentIndex, currentIndex + 5).show();
    currentIndex += 5;
    checkButton();
});

function checkButton() {
    var currentLength = $("#tableId tr:visible").length;

    if (currentLength >= x) {
        btnMore.hide();
    } else {
        btnMore.show();
    }


}
}

function dateFunction() {

  var today = new Date();
  var dd = today.getDate();
  var mm = today.getMonth() + 1; //January is 0!
  var yyyy = today.getFullYear();

  if (dd < 10) {
    dd = '0' + dd
  }

  if (mm < 10) {
    mm = '0' + mm
  }

  today = yyyy + '-' + mm + '-' + dd;
  document.getElementById('id_deadline').setAttribute("min", today);
}




  </script>
<html>

activities/templates/activities/choose_project_task.html
{% extends "activities\base.html" %}
{% block title %} Επιλογή αρμοδιότητας {% endblock %}

{% block maincontent %}
{% if messages %}
<p></p>
<div align="center">
  <div class="alert alert-success" role="alert">
  {% for message in messages %}
  {{ message }}
  {% endfor %}
  </div>
</div>
{% endif %}
<h2 style="text-align:center">Τροποποίηση αρμοδιοτήτων</h2>
{% if form.errors %}
<div align="left">
  <div class="alert alert-danger" role="alert">
      <ol>
        {% for field in form %}
          {% for error in field.errors %}
          <li>{{ field.label_tag }} {{ error|escape }}</li>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <li>{{ error|escape }}</li>
        {% endfor %}
      </ol>
   </div>
</div>
{% endif %}
  <form method ="POST" action="{% url 'activities:choose_project_task' project.id %}">
    {% csrf_token %}
    {{ form.project_id }}
	   <div class="form-group col-md-12">
       {{ form.project_task_id.label_tag }}
       {{ form.project_task_id }}
			</div>
			<button type ="submit" class="submit" style="float: right"><span class="glyphicon glyphicon-arrow-right"></span></button>
  </form>


{% endblock %}

activities/templates/activities/edit_task_form.html
{% extends "activities\base.html" %}
{% block title %} Τροποποίηση Αρμοδιότητας {% endblock %}
{% block maincontent %}
  <div align="center">
    <h1> Τροποποίηση Αρμοδιότητας </h1>
  </div>
  {% if form.errors %}
  <div align="left">
    <div class="alert alert-danger" role="alert">
        <ol>
          {% for field in form %}
            {% for error in field.errors %}
            <li>{{ field.label_tag }} {{ error|escape }}</li>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <li>{{ error|escape }}</li>
          {% endfor %}
        </ol>
     </div>
  </div>
  {% endif %}
  <form method="post" {% if parent_project %} action="{% url 'activities:edit_task' task_id=task.id parent_project_id=parent_project.id %}"
                      {% elif not parent_project %} action="{% url 'activities:edit_task' task_id=task.id %}" {% endif %}>
  {% csrf_token %}
    {{ form.task_id }}
    {{ form.project_id}}
    <div class="form-group col-md-12">
      {{ form.title.label_tag }}
      {{ form.title }}
    </div>
    <div class="form-group col-md-12">
      {{ form.deadline.label_tag }}
      {{ form.deadline }}
    </div>
    <div class="form-group col-md-12">
      {{ form.description.label_tag }}
      {{ form.description }}
    </div>
    <div class="form-group col-md-12">
      {{ form.receiver.label_tag }}
      {{ form.receiver }}
    </div>
    <div class="form-group">
        <div class="col-md-12">
          <a {% if parent_project %} href="{% url 'activities:choose_project_task_form'  project_id=parent_project.id %}" {% else %} href= "{% url 'activities:activities' %}" {% endif %} class="btn btn-default"><span class="glyphicon glyphicon-chevron-left"></span> Πίσω </a>

          <button type="reset" class="btn btn-default">
              <span class="glyphicon glyphicon-refresh"></span>
          </button>
          {% if parent_project %}
          <button type ="submit" name="continue" class="submit" style="float: right; margin: 0px;">Επιλογή επόμενης αρμοδιότητας</button>
          {% endif %}
          <br><br>
          <button type ="submit" name="done" class="submit" style="float: right; margin: 0px;"><span class="glyphicon glyphicon-floppy-disk"></span> Ολοκλήρωση</button>



        </div>
    </div>


  </form>
{% endblock %}

activities/templates/activities/index.html
{% load static %}
<html>
  <link rel="stylesheet" type="text/css" href="{% static 'activities/register_login.css' %}">

  <body>
    {% if messages %}
      {% for message in messages %}
      <div id="formFooter">
    		<a>{{ message }}</a>
    	</div>
      {% endfor %}
    {% endif %}

    <div class="wrapper fadeInDown">
      <div id="formContent">
        <div class="fadeIn first">
          <img src="https://www.dafni-ymittos.gov.gr/wp-content/uploads/2017/06/logosquare100.png" alt="Image" id="icon" alt="User Icon" style="width:100px; height: 100px;"/>
        </div>
        <form id="login-form" method="post" action="{% url 'activities:authenticate' %}">
          {% csrf_token %}
          {{form}}
          <button type="submit" class="submit" onclick="check(this.form)">ΣΥΝΔΕΣΗ</button>
        </form>
        <div id="formFooter">
          <a class="underlineHover" href="#">Δεν είστε εγγεγραμμένος/η;</a>
        </div>
      </div>
    </div>
</body>
  <script language="javascript">
  function check(form)
  {
  if(form.login.value!= "" && form.password.value!= ""){
  window.location.href="loginController.jsp";
  }
  else{
  document.getElementById("login").required= true;
  document.getElementById("password").required= true;
  alert( "Παρακαλώ συμπληρώστε όλα τα πεδία" );
  }
  }
  </script>
</html>